version: 2
updates:
  - package-ecosystem: poetry
    directory: "/"
    schedule:
      interval: monthly
      time: "12:00"
    open-pull-requests-limit: 10
    labels:
      - dependencies

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "12:00"
    labels:
      - ci-cd
